### ISSUE TITLE
Horizontal line wrap

### ISSUE THREAD

**Issue by giantss** [ArnaudRinquin/react-native-radio-buttons#101]
Thanks very much to the open source plug-in provided by the author, but I have a problem in the use process and I don't know how to solve it.
## ideal:
![image](https://user-images.githubusercontent.com/13778798/37706758-9c124ba4-2d3b-11e8-92c9-2e7168c809c9.png)
 What should I do? help me.

**Comment by ArnaudRinquin** [comment]
You can probably use something like `flexWrap: wrap` on the container element. Closing this issue as it's not related to the library but only to the general understanding of React Native.
