### ISSUE TITLE
Why deprecate?

### ISSUE THREAD

**Issue by xeruf** [ArnaudRinquin/react-native-radio-buttons#105]
The native component you mentioned is iOS only and has a lot less configuration possibilities. It is not even close to a replacement. Why did you deprecate this package in favor of it?

**Comment by keeprock** [comment]
Because maintainer don't want to compete with an official team with 6-figures salaries.

**Comment by ArnaudRinquin** [comment]
Hi there,

It's not a mater of competition. 

* I just don't have the time to maintain this
* I poorly designed it's API
* there is a much better alternative: https://github.com/react-native-community/react-native-segmented-control
