### ISSUE TITLE
allowFontScaling issue

### ISSUE THREAD

**Issue by GantMan** [ArnaudRinquin/react-native-radio-buttons#11]
allowFontScaling really messes up the navigation for devices that have the font scaling turned up.  I'd like to disable it.   I can't pass that property to SegmentedControls without completely restyling it from scratch via `renderOption`.   Can you please pass along allowFontScaling to the default text item so I can stop it?

May create a PR on this if restyling gets too unruly.

**Comment by GantMan** [comment]
See PR #12

**Comment by ArnaudRinquin** [comment]
dc49892d95352f62322d2090b261fd1f11830a04 Closes this issue.
