### ISSUE TITLE
text not centered vertically on Android

### ISSUE THREAD

**Issue by morenoh149** [ArnaudRinquin/react-native-radio-buttons#15]
![screen shot 2016-01-02 at 4 34 06 pm](https://cloud.githubusercontent.com/assets/587438/12076194/baed2972-b16e-11e5-8541-1115dc71115c.png)
any thoughts on why this might be?

I've tested this on ios and the issue is only present on Android.

**Comment by hanneskaeufler** [comment]
Can confirm, text is not vertically centered on android.

**Comment by csudanthi** [comment]
I ran into the same issue and resolved it.  See https://github.com/ArnaudRinquin/react-native-radio-buttons/pull/17

**Comment by ArnaudRinquin** [comment]
Fixed by #17

**Comment by morenoh149** [comment]
new npm release? @ArnaudRinquin

**Comment by ArnaudRinquin** [comment]
Like I said in #17, version `0.8.1` has been published.
