### ISSUE TITLE
way to make the segmented control read only?

### ISSUE THREAD

**Issue by manask88** [ArnaudRinquin/react-native-radio-buttons#18]
I have a usr case where i would like to prevent the user from making changes to selected option in the segmented control. Is there a way to do it?

**Comment by ArnaudRinquin** [comment]
It's pretty easy, you just pass `function(){}` as `onSelection` prop.

**Comment by manask88** [comment]
i just tried that. it doesnt seem to work.   I gave different background colors to the selected and unselected options. I can still click over other options and the background color for the new selection changes. What you suggested helps to ignore the callback after a selection, but it doesnt really prevent the segmented control component to change its internal state

**Comment by tomauty** [comment]
Can you make your `renderOption` function return a `<View>` instead?
