### ISSUE TITLE
container style doesn't work 

### ISSUE THREAD

**Issue by john916zhang** [ArnaudRinquin/react-native-radio-buttons#24]
I set a style to a SegmentedControls component, but the style doesn't work.

```
          <SegmentedControls
            style={styles.segmented}
            options={this.segmentValues}
            selectedIndex={segment}
            onChange={this._onChange}
          />
```

Please add the following line to function renderContainer of segmented-controls.js
`
    return <View style={[containerStyle, this.props.style]}>{options}</View>;
`

**Comment by ArnaudRinquin** [comment]
As you seem to know the exact required changes, could you please create a pull request?

**Comment by ArnaudRinquin** [comment]
I added `containerStyle` prop handling as a new feature in `0.9.0`. See [the implementation](https://github.com/ArnaudRinquin/react-native-radio-buttons/blob/master/lib/segmented-controls.js#L51).
