### ISSUE TITLE
Disable SegmentedControl based on a prop

### ISSUE THREAD

**Issue by varungupta85** [ArnaudRinquin/react-native-radio-buttons#30]
User should be able to disable the `SegmentedControl` component based on a prop. Similar functionality is present in `SegmentedControlIOS` in `react-native`. I added the support by using `pointerEvents` property for the container view in the `renderContainer` method but it may be a bit of a hack and wanted to discuss what other ways this can be achieved.

**Comment by ArnaudRinquin** [comment]
@varungupta85 PR welcome!
