### ISSUE TITLE
setState reseting radio buttons

### ISSUE THREAD

**Issue by fbonesso** [ArnaudRinquin/react-native-radio-buttons#34]
Hi,

Everytime when I call this.setState in anywhere in view my segmented buttons are reseted to original value, anyone knows what this could be?

Thanks!

**Comment by joenoon** [comment]
@fbonesso can you paste a simple example?  Without seeing it, my guess would be when you call setState from above, a re-render it triggered, and your `selectedOption` is stale or hard-coded.  For example:

```
      <SegmentedControls
        options={[
          'Option1',
          'Option2'
        ]}
        onSelection={this.onSelect}
        selectedOption={'Option2'}
      />
```

If something triggers that to re-render, it will always get set back to Option2.  So it should be keeping its option selection in state too:

```
      <SegmentedControls
        options={[
          'Option1',
          'Option2'
        ]}
        onSelection={this.onSelect}
        selectedOption={this.state.selectedOption}
      />
```

**Comment by ArnaudRinquin** [comment]
Thanks for helping @joenoon, I'll close this one as you never got an answer.
