### ISSUE TITLE
Segment Element in React Native

### ISSUE THREAD

**Issue by akd6162** [ArnaudRinquin/react-native-radio-buttons#35]
My segment  element is not showing the container Radius not even default radius of border

**Comment by ArnaudRinquin** [comment]
No way to help you with so few details.

**Comment by akd6162** [comment]
I want use Segment element as Radio button for gender(Male,Female) selection.
But the container Radius of Segment is  not rendering in proper way. One more thing...
When I click on the the Segment element entry. The color field which come after I click ....is not appear round corner. it come as a rectangle.
