### ISSUE TITLE
SegmentedControls style not working

### ISSUE THREAD

**Issue by menoy** [ArnaudRinquin/react-native-radio-buttons#36]
Hi, I try using your SegmentedControls in RN v. 0.28.0 but it seems the style for selected item didn't work. Meanwhile the touchable without feedback function for selected item is working fine (I can see the item being selected by calling the variable I inputted, but the style doesn't change and in neutral state).

It was working fine in RN v.0.26 but when I update the RN to v.0.28.0 it appears that the styling doesn't working, also for segmented controls container position in version 0.12.0 can't be override and seems broke, so I reverting to use version 0.11.0. 
Thanks.

Kindly wait for your respond.
![bug-segmenteditem](https://cloud.githubusercontent.com/assets/3962062/17164510/1ab06c94-53f3-11e6-9c77-49116d956c4c.PNG)

**Comment by GantMan** [comment]
I'm having the same issue
![image](https://cloud.githubusercontent.com/assets/997157/17643819/c7e015dc-613a-11e6-9aa5-4728be2c5763.png)

**Comment by GantMan** [comment]
fixed, will PR
![screen shot 2016-08-13 at 3 11 13 pm](https://cloud.githubusercontent.com/assets/997157/17645325/44b6c006-6168-11e6-81ed-bae398294ed9.png)

**Comment by joenoon** [comment]
@GantMan could you try this instead (probably undocumented):

```
<SegmentedControls
  ...
  optionContainerStyle={{
    flex: 1
  }}
  ...
/>
```

The default is currently spaced more like the Apple apps.. appstore, itunes style (bottom example).

![simulator-screen-shot-aug-13 -2016 -1 16 06-pm](https://cloud.githubusercontent.com/assets/5726/17645366/baa76cee-6158-11e6-9293-fd95146617d7.png)

**Comment by GantMan** [comment]
@This accomplishes the same thing, but the code is the same.  Looking at where that property gets merged, is by the merge with `baseOptionContainerStyle`, which is where I was placing my change.

I have 3 segmented controls throughout my app.  I would rather add code that fixes it once, in one place, rather than to have to add that style to all 3, especially when without it, it looks broken.

**Comment by joenoon** [comment]
I think it's just about what the right default should be then.  If flex:1 was the default, I'd have to add flex:null throughout my app's segmented controls - the opposite of you having to add flex:1 to yours.

If people want the default to be flex:1 I'm happy to change my app to accommodate.

But I think there is something else in your example that is making it look broken.  The default as of now shouldn't stretch like that to begin with.  Do you have a flex:1 on the control directly?  By default it should be more like my bottom example, where it just takes up the space needed.

Here is some context:

https://github.com/ArnaudRinquin/react-native-radio-buttons/pull/33
https://github.com/ArnaudRinquin/react-native-radio-buttons/commit/6f9acd93354df489ecf80910e87ac576df517d0d

**Comment by GantMan** [comment]
Usually SegmentedControls has behaved this way for me in the past.   Perhaps we should have a test project that states the way things "SHOULD" be, and then we style to match it.  I only know that upgrading react native versions broke all my `SegmentedControls` where they originally looked and behaved this way before.

**Comment by GantMan** [comment]
So where do we go from here @ArnaudRinquin ?

**Comment by lorensr** [comment]
`optionContainerStyle={{ flex: 1 }}` and setting a width on container worked for me, but should be the default and be clear from docs. Made me think the lib was broken.

**Comment by ArnaudRinquin** [comment]
@GantMan Sorry I neglected this issue (and the others). I'm OK with both solutions really. I'd suggest to use whatever is the closest to the native components.

**Comment by GantMan** [comment]
Let's close this issue for now.  I see you've been busy these holidays!
