### ISSUE TITLE
Seems to only want RN 0.8.0.  What about newer versions?

### ISSUE THREAD

**Issue by pedramsaleh** [ArnaudRinquin/react-native-radio-buttons#4]
It doesn't seem like I can upgrade past React Native 0.8.0 because of a dependency of this package for only that RN version.  Is there a reason it's stuck on that version?  Can you change the dependency to remove that restriction and let it accept newer versions of RN?

**Comment by quantuminformation** [comment]
+1

**Comment by ryanmcdermott** [comment]
+1

**Comment by ArnaudRinquin** [comment]
Sorry guys I have been pretty busy lately. Working on it.

**Comment by quantuminformation** [comment]
Thanks!

**Comment by pedramsaleh** [comment]
+1

**Comment by jeremiecarlson** [comment]
+1

**Comment by manask88** [comment]
ive been using this with react 13.2 and its working for me (ive used segmented controls only).  Can you please tell when do you expect this to be updated?

**Comment by ArnaudRinquin** [comment]
I am so sorry I can't find the time to update this.

Technically, nothing but `package.json` needs to be updated, but I'd like to update the example as well.

PR are welcome, I don't think it's a lot of work really, but I am not sure I can afford spending some on this at the moment.

**Comment by manask88** [comment]
Hey @ArnaudRinquin , ive created a PR https://github.com/ArnaudRinquin/react-native-radio-buttons/pull/5. I bumped up RN version in package.json and also updated the example. Let me know what you think.

**Comment by ArnaudRinquin** [comment]
#5 by @manask88 fixes this issue and I just published `0.6.0`.

Thanks again @manask88
