### ISSUE TITLE
Issue with Array of objects

### ISSUE THREAD

**Issue by geecurve** [ArnaudRinquin/react-native-radio-buttons#43]
Keep getting this error:

Objects are not valid as a React child (found: object with keys {label, value}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `Text`.

**Comment by sbefort** [comment]
I had the same issue.  Make sure you have `extractText={ (option) => option.label }` as a prop.

**Comment by geecurve** [comment]
Thanks will give it a try. I did remedy the situation by using simple array
as a work around but this property I hope will make difference to use the
component properly.

**Comment by summersky92** [comment]
Same issue for me at the first time, then go through the examples find the answer
https://github.com/ArnaudRinquin/react-native-radio-buttons/blob/master/examples/index.ios.js#L272
