### ISSUE TITLE
Small error in documentation - Dead link to babel example

### ISSUE THREAD

**Issue by MossP** [ArnaudRinquin/react-native-radio-buttons#47]
As title suggests, the link to https://github.com/ArnaudRinquin/react-native-radio-buttons/blob/master/examples/.babelrc is dead.

**Comment by GantMan** [comment]
Where is this link in documentation?  DO you want to submit a small PR?

**Comment by MossP** [comment]
I considered that but I don't see where it's supposed to point to. I have a feeling it may be an outdated line?

it's in the install section of the [readme.md](https://github.com/ArnaudRinquin/react-native-radio-buttons/blob/master/README.md)
