### ISSUE TITLE
custom segment render

### ISSUE THREAD

**Issue by funkysoul** [ArnaudRinquin/react-native-radio-buttons#52]
When using a custom renderer like on your example, I'm not able to click the segment itself, I need to click the top border itself of the segment to be able to select. 
Any Idea what could be wrong?

```js
renderOption(option, selected, onSelect, index){
  const style = selected ? { fontWeight: 'bold'} : {};
  return (
    <TouchableWithoutFeedback onPress={onSelect} key={index}>
      <View>
        <Text style={style}>{option.label}</Text>
        <Text style={style}>{option.msg}</Text>
      </View>
    </TouchableWithoutFeedback>
  );
}

renderContainer(){
  return <View>{RadioButtons.renderVerticalContainer}</View>;
}
```

**Comment by ArnaudRinquin** [comment]
There is no obvious mistake in that piece of code. Have you found a solution to your issue?

**Comment by funkysoul** [comment]
nope not really.. I decided to write my own segmented button module.

**Comment by ArnaudRinquin** [comment]
>  I decided to write my own segmented button module.

Good choice! 

The simplicity of such a component isn't worth the struggle with external libraries ;)
