### ISSUE TITLE
SegmentedControl direction='column' is showing as empty in iOS Simulator

### ISSUE THREAD

**Issue by davidsharp** [ArnaudRinquin/react-native-radio-buttons#57]
```
<SegmentedControls
  options={ ["5-blah blah blah","4-bleh bleh bleh","3-foo bar baz", "2-electric boogaloo", "1-jinkies"] }
  onSelection={ option=>that.setState({option}) }
  selectedOption={ state.option }
  direction='column'
/>
```
![screen shot 2017-01-05 at 09 50 36](https://cloud.githubusercontent.com/assets/5731838/21676326/2048c08e-d32d-11e6-9997-74533519f0ee.png)

While without the `direction='column'`, I'm getting:
![screen shot 2017-01-05 at 09 50 19](https://cloud.githubusercontent.com/assets/5731838/21676343/30ce1210-d32d-11e6-9f7e-8afc1b39b909.png)

`RadioButtons` seems to display properly, but I'd like to be able to use this JS-based SegmentedControls.

**Comment by neel132-zz** [comment]
Same issue on Android Emulator.

**Comment by anaskhan96** [comment]
Encountering the same problem on my Android.
@ArnaudRinquin could you shed some light on this?

**Comment by ArnaudRinquin** [comment]
I have absolutely no time for that. PR welcome.
