### ISSUE TITLE
TouchableWithoutFeedback does not work well with Text children.

### ISSUE THREAD

**Issue by sdrabb** [ArnaudRinquin/react-native-radio-buttons#61]
i've this warning: **Warning: TouchableWithoutFeedback does not work well with Text children. Wrap children in a View instead. See RadioButtons**

with that code 

             `<RadioButtons
                options={ this.state.options }
                onSelection={(selectedOption, selectedIndex) => {console.log(selectedOption)}  }
                renderOption={ (option, selected, onSelect, index) =>{
                  return (

                   <TouchableWithoutFeedback onPress={onSelect} key={index}>

                       <Text >{option}</Text>

                   </TouchableWithoutFeedback>
                 );
                }}
                renderContainer={(optionNodes) =>{return <View>{optionNodes}</View> } }

              />`

how i can solve?

**Comment by BrunoVillanova** [comment]
You need to put the Text inside a View

**Comment by Jakevin** [comment]
I replace use TouchableOpacity.

It's work well

**Comment by rajnishcoder** [comment]
@Jakevin `TouchableOpacity` will work but it may damage UI, best solution is as @BrunoVillanova  said.

**Comment by I-O-O-I** [comment]
THIS WORKS https://github.com/facebook/react-native/issues/10180#issuecomment-298375648
