### ISSUE TITLE
segmentedControl

### ISSUE THREAD

**Issue by aureldev** [ArnaudRinquin/react-native-radio-buttons#65]
Hi,
colors on segmented control arent working when I apply a redux state or component state action on it
 something
`handleRadio(text,index){
		switch(index){
			case 0:
				this.props.selected(index); //could use component state for that but they both don't work
				console.log(this.props.whoIsSelected);
			case 1:
				this.props.selected(index);
				console.log(this.props.whoIsSelected);
		}
	}`
`<SegmentedControls
					style={{padding:5,margin:5}}
					options={options}
					tint={'#007AFF'}
					selectedTint={'white'}
					allowsFontScaling={false}
					onSelection={this.handleRadio.bind(this)}
				/>`

**Comment by ArnaudRinquin** [comment]
I can't read anything. Please make an effort to write a proper issue.
