### ISSUE TITLE
Android fix for border radius hides last separator

### ISSUE THREAD

**Issue by randycoulman** [ArnaudRinquin/react-native-radio-buttons#66]
After upgrading to 0.14.0, we noticed that the last separator in our `SegmentedControls` was no longer showing on Android.  iOS continues to work fine.

0.13.0:
![screen shot 2017-02-01 at 1 48 36 pm](https://cloud.githubusercontent.com/assets/1406203/22528344/bb97cdae-e887-11e6-8ad3-f028039d1199.png)

0.14.0:
![screen shot 2017-02-01 at 1 46 48 pm](https://cloud.githubusercontent.com/assets/1406203/22528335/b39ac50c-e887-11e6-9b7c-5db5087a2749.png)

After some digging and debugging, what appears to be happening is that the addition of the `borderRadius*` properties to the right edge of the last option is also clipping the border on the left.

This appears to be caused by https://github.com/facebook/react-native/issues/11042.

As a result, it may be best to just wait for an upstream fix (https://github.com/facebook/react-native/pull/11706), but there may be some kind of workaround we could do here until that happens.

One idea I have is to apply the separator style properties to the right border of the next-to-last option, rather than the left border of the last option.  This is an ugly hack, but would work around the issue.

**Comment by wuxudong** [comment]
https://github.com/facebook/react-native/pull/11706 is already closed.

and I update react-native to 0.42.0, but the problem still exists ?

**Comment by America-first-melon** [comment]
@wuxudong  fixed?

**Comment by Rawphs** [comment]
Setting `containerBorderRadius` to zero is a workaround if you don't mind having square buttons.
