### ISSUE TITLE
Propose flexible custom style from caller

### ISSUE THREAD

**Issue by Kudo** [ArnaudRinquin/react-native-radio-buttons#7]
There is a bug https://github.com/facebook/react-native/issues/3233 for Android RN that set padding on Text will have unexpected result.
So my segmented control text did not vertically centered.

Currently SegmentedControls' design is not flexible enough. For example, if I want to set fontSize for the text, there is no way to do that.
Do you consider to accept style prop and let caller to decide the style?
Something like [MapView style prop](https://github.com/facebook/react-native/blob/master/Libraries/Components/MapView/MapView.js#L95) and [caller sample](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/MapViewExample.js#L193-L194) .

If you don't mind for the design changes, I can take some time to propose a PR. Thanks.

**Comment by ArnaudRinquin** [comment]
Thanks to #8 from @johanneshilden, you can now use the `SegementedControl` `renderOption` prop to override the default which just uses `Text`.

**Comment by Kudo** [comment]
The solution works fine for me.  Thanks @ArnaudRinquin @johanneshilden
