### ISSUE TITLE
The Dividing line has disappeared

### ISSUE THREAD

**Issue by hnty545** [ArnaudRinquin/react-native-radio-buttons#80]
![-3](https://user-images.githubusercontent.com/6417805/28000559-f90beca8-6558-11e7-8372-3b11fddf2fca.jpg)

————————————
this._statusOptions = [
	{ key: '', value: '全部' },
	{ key: '0', value: '未开通' },
	{ key: '1', value: '已开通' },
	{ key: '2', value: '已停用' }
]

<SegmentedControls
                            tint={COLOR.theme}
                            options={this._statusOptions}
                            extractText={(option) => option.value}
                            onSelection={this._selectedStatus}/>

**Comment by iyadthayyil** [comment]
The Fix is here : https://github.com/ArnaudRinquin/react-native-radio-buttons/pull/75

**Comment by hnty545** [comment]
thanks!
suggest updating to npm.

**Comment by hnty545** [comment]
@ArnaudRinquin

**Comment by ArnaudRinquin** [comment]
Should good now ;)
