### ISSUE TITLE
Release notes for version 1.0.0

### ISSUE THREAD

**Issue by almirfilho** [ArnaudRinquin/react-native-radio-buttons#85]
Hi @ArnaudRinquin, could you please publish the release notes for the version 1.0.0?
I want to upgrade to the new version, but upgrading without knowing what changed is, besides hard, not a good practice.

Thanks for the awesome package =)

**Comment by ArnaudRinquin** [comment]
Oh sure, I'll do it ASAP.

In the meantime: I updated to a major following #84 as `prop-types` is now a peerDependency (instead of using `React.PropTypes`). Other that that it's just bug fixes from latests PRs.

**Comment by almirfilho** [comment]
Thank you very much.
