### ISSUE TITLE
Update Segment via code

### ISSUE THREAD

**Issue by GantMan** [ArnaudRinquin/react-native-radio-buttons#9]
Trying to update what segment is selected via code (Not user action), and having trouble.

Updating the `selectedOption` property and re-rendering is not working, probably because the component is not mounting again?

Anyhow, I wanted to selectOption, but that function is not accessible with the segmented control wrapper.  Perhaps a ref?

**Comment by ArnaudRinquin** [comment]
The only _right_ way to select an option is to use the `selectedOption` prop. Accessing and updating react elements is definitely wrong (ie. not the react way).

> Updating the selectedOption property and re-rendering is not working, probably because the component is not mounting again?

You are right, we do copy `selectedOption` from `props` to `state` at mount time so we should copy it again everytime you change props. This is the right fix to apply. I'll do it.

**Comment by ArnaudRinquin** [comment]
I just pushed the fix in 3487d15

See the implementation [details](https://github.com/ArnaudRinquin/react-native-radio-buttons/blob/master/lib/radio-buttons.js#L36)

**Comment by GantMan** [comment]
Awesome man!   I didn't want to assume changing it at that level, but glad you did.  Glad you took the time to fix :+1:
