### ISSUE TITLE
SegmentedControls style issue (container border radius)

### ISSUE THREAD

**Issue by VovaSokol** [ArnaudRinquin/react-native-radio-buttons#99]
Hi! Sorry for my english. 
"react-native": "^0.49.5",
"react-native-radio-buttons": "^1.0.0",
![untitled-1](https://user-images.githubusercontent.com/21169523/36062966-6d051ba2-0e87-11e8-99ec-5c22eb1714c6.jpg)

I fixed it just add 'else' in node_modules/react-native-radio-buttons/lib/segmenteg-controls.js:121
last 'if' rewrited first 'if'
```
        if (index === 0) {
          borderRadiusStyle =  config.direction === 'row' ?
            {
              borderTopLeftRadius: adjustedBorderRadius,
              borderBottomLeftRadius: adjustedBorderRadius
            } : {
              borderTopLeftRadius: adjustedBorderRadius,
              borderTopRightRadius: adjustedBorderRadius
            };
        }  else if (index === this.props.options.length - 1) {
          borderRadiusStyle =  config.direction === 'row' ?
            {
              borderTopRightRadius: adjustedBorderRadius,
              borderBottomRightRadius: adjustedBorderRadius
            } : {
              borderBottomLeftRadius: adjustedBorderRadius,
              borderBottomRightRadius: adjustedBorderRadius
            }
        }else // <------ here
        if (index === this.props.options.length - 2) {
          borderRadiusStyle =  config.direction === 'row' ?
            {
              borderRightWidth: config.separatorWidth,
              borderRightColor: config.separatorTint,
            } : {
              borderBottomWidth: config.separatorWidth,
              borderBottomColor: config.separatorTint,
            }
        }
```
resault 
![untitled-2](https://user-images.githubusercontent.com/21169523/36063106-9ed34bde-0e89-11e8-852f-6eb753568656.jpg)

**Comment by joenoon** [comment]
I have not used this in a while, but my last working code was this and didn't have this problem:

```
<SegmentedControls
  tint={'blue'}
  optionStyle= {{
    fontSize: 16,
    paddingHorizontal: 20
  }}
  optionContainerStyle= {{
    flex: 1,
  }}
  options={[
    'Foo',
    'Bar'
  ]}
  onSelection={this.onSelect}
  selectedOption={this.props.selected.value}
/>
```

Maybe post your code or check to see if you have a backgroundColor set anywhere that might cause this.  Or if you use `<Text>` or `<View`> elements, make sure they are `{backgroundColor: 'transparent'}`.

**Comment by pedrodevoto** [comment]
Having the same issue, but the problem is that if I add that `if`, I get no middle separator.

Before:
><img width="340" alt="screen shot 2018-02-16 at 21 46 33" src="https://user-images.githubusercontent.com/605227/36336015-00b80a0a-1363-11e8-8b4b-372e7980795b.png">

After:
><img width="340" alt="screen shot 2018-02-16 at 21 46 00" src="https://user-images.githubusercontent.com/605227/36336027-1409758a-1363-11e8-9789-57ee7e294cd9.png">

RN 0.48.4

**Comment by pedrodevoto** [comment]
Had `backTint` set to a specific color. Setting it to `'transparent'` solved the issue 😃

**Comment by VovaSokol** [comment]
Thanks! It solved!
